/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;
import com.model.M_Pendaftaran;
import com.entity.Pendaftaran;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.entity.Pendaftaran;
/**
 *
 * @author danil
 */
public class V_List_Pendaftaran extends javax.swing.JFrame {
    
  final  M_Pendaftaran m_pe = new M_Pendaftaran();
   final  Pendaftaran p = new Pendaftaran();
    /**
     * Creates new form V_List_Pendaftaran
     */
    public V_List_Pendaftaran() {
        initComponents();
        txtCariPendaftaranSiswa.requestFocus();
      try {
          m_pe.setFilterTahunAjaran(this);
          m_pe.viewPendaftaran(p,tblPendaftaranSiswa);
      } catch (SQLException ex) {
          Logger.getLogger(V_List_Pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
      }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPendaftaranSiswa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCariPendaftaranSiswa = new javax.swing.JTextField();
        CBurutan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CBTahunAjaranFilter = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnCetakPerSiswa = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("List Pendaftaran");

        btnExit.setText("X");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Pendaftaran"));

        tblPendaftaranSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblPendaftaranSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPendaftaranSiswaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPendaftaranSiswa);

        jLabel2.setText("Cari :");

        txtCariPendaftaranSiswa.setBackground(new java.awt.Color(255, 102, 102));
        txtCariPendaftaranSiswa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPendaftaranSiswaKeyReleased(evt);
            }
        });

        CBurutan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-", "NO PENDAFTARAN", "USIA" }));
        CBurutan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBurutanActionPerformed(evt);
            }
        });

        jLabel3.setText("Urut Berdasarkan :");

        jLabel4.setText("Tahun Ajaran :");

        CBTahunAjaranFilter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-PILIH-" }));
        CBTahunAjaranFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTahunAjaranFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBTahunAjaranFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CBurutan, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariPendaftaranSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCariPendaftaranSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CBurutan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(CBTahunAjaranFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCetak.setText("CETAK");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnCetakPerSiswa.setText("CETAK PER SISWA");
        btnCetakPerSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakPerSiswaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCetakPerSiswa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit)
                    .addComponent(btnCetak)
                    .addComponent(btnCetakPerSiswa)))
        );

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void tblPendaftaranSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPendaftaranSiswaMouseClicked
       m_pe.klikTabelPendaftaran(p, tblPendaftaranSiswa);
        System.out.println("tgl pindah sekolah= " +p.getAsalPindahTanggal());
      // System.out.println("select = "+p.getNoPendaftaran()+"="+p.getBioAnakKe()+"+"+p.getBioJmlSaudaraKandung());
    }//GEN-LAST:event_tblPendaftaranSiswaMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
      try {
          m_pe.deletePendaftaran(p, tblPendaftaranSiswa);
      } catch (SQLException ex) {
          Logger.getLogger(V_List_Pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtCariPendaftaranSiswaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPendaftaranSiswaKeyReleased

        try {
          p.setKeySearcing(txtCariPendaftaranSiswa.getText());
          m_pe.viewPendaftaran(p, tblPendaftaranSiswa);
      } catch (SQLException ex) {
          Logger.getLogger(V_List_Pendaftaran.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_txtCariPendaftaranSiswaKeyReleased

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       new V_Pendaftaran(p.getNoPendaftaran(),p.getBioNamaLengkap(),p.getBioNamaPanggilan(),p.getBioJenisKelamin(),p.getBioTempatLahir(),p.getBioTanggalLahir(),p.getBioAgama(),p.getBioKewarganegaraan(),p.getBioAnakKe(),p.getBioJmlSaudaraKandung(),p.getBioJmlSaudaraTiri(),p.getBioJmlSaudaraAngkat(),p.getBioBahasaSehariHari(),p.getBioBeratBadan(),p.getBioTinggiBadan(),p.getBioGolonganDarah(),p.getBioPenyakitBeratYangPernahDiderita(),p.getBioAlamatTempatTinggal(),p.getBioNoTlp(),p.getBioBertempatTinggal(),p.getWaliNamaAyahKandung(),p.getWaliNamaIbuKandung(),p.getWaliPendidikanTertinggiIbu(),p.getWaliPendidikanTertinggiAyah(),p.getWaliPekerjaanAyah(),p.getWaliPekerjaanIbu(),p.getWaliNamaWaliSiswa(),p.getWaliPendidikanTertinggiWaliSiswa(),p.getWaliHubunganTerhadapAnak(),p.getWaliPekerjaanWaliSiswa(),p.getWaliPendapatanPerbulanOrangTua(),p.getAsalMasukSekolah(),p.getAsalAnak(),p.getAsalTkNamaTk(),p.getAsalTkNomoTahunSuratKeterangan(),p.getAsalTkLamaBelajar(),p.getAsalPindahNamaSekolahAsal(),p.getAsalPindahTanggal(),p.getAsalPindahDariKelas(),p.getAsalDiterimaSekolahTanggal(),p.getAsalDiterimaDikelas(),p.getKodeTahunAjaran(),p.getLampiranAkteKelahiran(),p.getLampiranKk(),p.getLampiranKtpOrtu(),p.getLampiranFotoOrtu(),p.getLampiranFotoAnak(),p.getTahunAjaran(),p.getSemester()).setVisible(true);
       dispose();
    }//GEN-LAST:event_btnEditActionPerformed

    private void CBurutanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBurutanActionPerformed
        try {
            p.setSortingview(CBurutan.getSelectedItem().toString());
            m_pe.viewPendaftaran(p, tblPendaftaranSiswa);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_CBurutanActionPerformed

    private void CBTahunAjaranFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTahunAjaranFilterActionPerformed
        // TODO add your handling code here:
        try {
            p.setFilterTahunAjaran(CBTahunAjaranFilter.getSelectedItem().toString());
            System.out.println(p.getFilterTahunAjaran());
            m_pe.viewPendaftaran(p, tblPendaftaranSiswa);
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_CBTahunAjaranFilterActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        String thnAjaran = CBTahunAjaranFilter.getSelectedItem().toString();
        String url;
        String sorting = CBurutan.getSelectedItem().toString();
        
        if(sorting.equals("-PILIH-") || thnAjaran.equals("-PILIH-")){
             JOptionPane.showMessageDialog(null, "Pilih Urutan Cetak...!!!");
        }else if(sorting.equals("NO PENDAFTARAN")){
            url = "./src/laporan/laporanPendaftaranSortingNo.jrxml";
            m_pe.setLaporanPendaftaran(thnAjaran, url);
        }else{
            url = "./src/laporan/laporanPendaftaran.jrxml";
            m_pe.setLaporanPendaftaran(thnAjaran, url);
        }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnCetakPerSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakPerSiswaActionPerformed
        // TODO add your handling code here:
        //String cari = txtCariPendaftaranSiswa.getText();
        String url = "./src/laporan/cetaksiswa.jrxml";
        m_pe.setCetakPerSiswa(p.getNoPendaftaran(), url);
    }//GEN-LAST:event_btnCetakPerSiswaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_List_Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_List_Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_List_Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_List_Pendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_List_Pendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> CBTahunAjaranFilter;
    private javax.swing.JComboBox<String> CBurutan;
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnCetakPerSiswa;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPendaftaranSiswa;
    private javax.swing.JTextField txtCariPendaftaranSiswa;
    // End of variables declaration//GEN-END:variables
}
